# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-12 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='cnf_password',
            field=models.CharField(default='pass', max_length=100),
        ),
    ]
